### ISSUE TITLE
No Example Found when doing bundle exec rspec

### ISSUE THREAD

**Issue by zpfdev** [akabiru/todos-api#10]
I have followed thru Part 1 where I set up the item_spec.rb and todo_spec.rb and execute it with bundle exec rspec. Instead of showing the failures, it shows no example found.

**Comment by gderuki** [comment]
@zpfdev Do you have a GitHub repository that have your code, so I could reproduce this error?

**Comment by zpfdev** [comment]
yes, i just uploaded my repository

**Comment by zpfdev** [comment]
Ok, the problem is that I execute the command in todos-api/spec. I went back to the parent directory, which is todos-api/ and ran the command again. This time, it worked.
