### ISSUE TITLE
Possible typo on Part 1?

### ISSUE THREAD

**Issue by zpfdev** [akabiru/todos-api#13]
In Part 1, under the TodoItems API, i noticed that the RSpec "item_spec.rb" is actually stored under app/requests/.

Also I checked with the source code, there isn't such folder in App directory, so I believe this is a typo?

**Comment by akabiru** [comment]
@zpfdev Good shout, updating ASAP. 🙂

**Comment by akabiru** [comment]
Done. It's supposed to be in `spec/auth/items_spec.rb`
![screen shot 2018-01-10 at 18 19 43](https://user-images.githubusercontent.com/17295175/34779998-f1b5f5dc-f632-11e7-82fe-873879e826f1.jpg)
