### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by saviofreitas** [akabiru/todos-api#14]
Any strategy to invalidate access ? expire the token?

**Comment by akabiru** [comment]
Off the top of my head, you may want to handle this in the frontend by discarding the token given the timeout is relatively short i.e. 24 hours. Alternatively, you can keep track of disallowed tokens in the backend and validate against those before authorization.

**Comment by coisnepe** [comment]
@saviofreitas The way I'm handling it in my Vue app is: when the user signs in and the credentials are valid, return a JWT expiring 24 hours later, and set a _userSignedIn_ to _true_ in the app's state. When the user does an action that requires to be authenticated, the token is sent to the server along with the request. If the token is invalid/expired, the request is returned with an 'invalid' message and the token is removed from _localstorage_, as well as toggling _userSignedIn_ to _false_. Not sure if it's the canonical way to do it, but it gets the job done...

**Comment by saviofreitas** [comment]
It's a good alternative. In my case, these are applications in a corporate environment. Even removing the token from storage, it remains valid until it expires. This is the biggest complication I get.

**Comment by akabiru** [comment]
Cool. Let us know how you fair on. 👍  Give us a shout if otherwise. 🙂
