### ISSUE TITLE
Test case errors

### ISSUE THREAD

**Issue by dawa-liverpudlian** [akabiru/todos-api#21]
Hi austin,

I have done the same thing as you have shown, but somehow my factory doesn't seem to be working properly. i have attached the test case error in the picture. 
Hopefully you can tell me what's wrong with it.

Regards,
Dawa.
![factory error](https://user-images.githubusercontent.com/23231113/37141737-058b5e1e-22dc-11e8-8712-d41e6fb7e9d7.png)
![validation error](https://user-images.githubusercontent.com/23231113/37141746-0d2070ba-22dc-11e8-9288-6f74c8045cd9.png)

**Comment by akabiru** [comment]
Hey @dawa-liverpudlian , maybe confirm that the factories are in the correct directory and named correctly.

![screen shot 2018-03-08 at 12 35 21](https://user-images.githubusercontent.com/17295175/37143781-317cee52-22cd-11e8-96b7-5e2415ee8c02.jpg)

**Comment by dawa-liverpudlian** [comment]
Hey Austin, it's in correct directory under specs and named correctly too.
![todos](https://user-images.githubusercontent.com/23231113/37144112-155041a0-22e3-11e8-997c-9a8674f3a7a7.png)

**Comment by akabiru** [comment]
Hmm, and you have the `factory_bot_rails` not `factory_bot` in your Gemfile?
https://github.com/akabiru/todos-api/blob/master/Gemfile#L36-L37

**Comment by dawa-liverpudlian** [comment]
Yes i have factory_bot_rails. I guess it's because i am using newest version of rails i.e 5.1.5 & ruby 2.5.0.
Seems like that from documentation page of factory bot rails.

**Comment by dinerdaniel** [comment]
This fix it for me. 

First 
in spec/requests/todos_spec.rb
change the word json
from lines
 expect(json).not_to be_empty
      expect(JSON.size).to eq(5)

To 

  expect(:todos).not_to be_empty
      expect(:todos.size).to eq(5)


Then
in 
### spec/requests/todos_spec.rb
Just change the validation number from 10 to 5 


RSpec.describe 'Todos API', type: :request do

  **let!(:todos) { create_list(:todo, 5) }**
  let(:todo_id) { todos.first.id }
  puts :todos

  describe 'GET /todos' do
  
    before { get '/todos'}

    it 'returns todos' do

      expect(:todos).not_to be_empty
      **expect(:todos.size).to eq(5)**
    end

**Comment by akabiru** [comment]
https://github.com/akabiru/todos-api#please-note
