### ISSUE TITLE
Adjustment for rails 5.2.0

### ISSUE THREAD

**Issue by ksdputra** [akabiru/todos-api#23]
Hi, Austin. Thanks for the great tutorial.

I found one adjustment for your tutorial. Since rails 5.2.0 doesn't generate secret.yml but credentials.yml.enc, the HMAC_SECRET in app/lib/json_web_token.rb should be

`HMAC_SECRET = Rails.application.credentials.read`

If the HMAC_SECRET still using secret_key_base, it will throw status 500 error with exception: 

`"#<TypeError: no implicit conversion of nil into String>`

This adjustment for rails 5.2.0 only for this time. Again, I thank you for your great tutorials.

**Comment by akabiru** [comment]
Heya @thekingisme Cheers for reaching out! Brilliant shout - would you be Ok to raise A PR for this? I'm looking to schedule some time to update the tutorial to Rails 5.2.0 - it can be merged then. 🙂

**Comment by dhurba87** [comment]
https://github.com/akabiru/todos-api/pull/28

**Comment by akabiru** [comment]
https://github.com/akabiru/todos-api#please-note
