### ISSUE TITLE
Why do I have to get the current_user todos only?

### ISSUE THREAD

**Issue by ahmadabdelhalim** [akabiru/todos-api#25]
I don't understand why did you get current_user.todos only, what if I want to allow the user to do anything as long as he's logged in? how can I achieve that with JWT instead of adding current_user to the controllers?

**Comment by akabiru** [comment]
Hey @ahmadabdelhalim , this is a sample design decision- generally, you don't want to expose peoples data unless you're building an "open" system where everyone can see what everyone else has been up to.

**Comment by ahmadabdelhalim** [comment]
I wanna know how can I let the user access anything as long as he's logged in. I don't know how can I achieve that using JWT.

**Comment by akabiru** [comment]
In the TodosController, you can amend `current_user.todos` to `Todo.all` to return all todos.
