### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Eosis** [akabiru/todos-api#29]
Thanks for a great tutorial!

I notice that you haven't got any licensing information about the code either here or on the scotch.io website. I'm guessing from the tutorial that you want others to use the code, but unfortunately the default copyright it has currently doesn't allow that.

Would you consider licensing this with a permissive license to allow others to build on it? 

https://choosealicense.com/ is a good resource for helping choose the license you want. Rails itself is under an MIT license which could be easily altered for your use. :)

**Comment by akabiru** [comment]
Hey @Eosis , thanks for the heads up! Definitely, want to share this with people. I think MIT license will do. 🙂

**Comment by akabiru** [comment]
Closed in #67
