### ISSUE TITLE
Error importing RequestSpecHelper, json is undefined

### ISSUE THREAD

**Issue by jraczak** [akabiru/todos-api#3]
I've followed along with the tutorial but am getting an error running the specs after the tasks API is implemented. Specifically, my remaining failures are because `json` seems to be undefined, so the import of that helper module doesn't seem to be correct. My import looks like the following:

```ruby
rails_helper.rb
....
ActiveRecord::Migration.maintain_test_schema!

# require database cleaner at the top level
require 'database_cleaner'

# [...]
# configure shoulda matchers to use rspec as the test framework and full matcher libraries for rails
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end

# [...]
RSpec.configuration do |config|
  # [...]

  config.include RequestSpecHelper, type: :request

  # start by truncating all the tables but then use the faster transaction strategy the rest of the time.
  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
    DatabaseCleaner.strategy = :transaction
  end

  # start the transaction strategy as examples are run
  config.around(:each) do |example|
    DatabaseCleaner.cleaning do
      example.run
    end
  end
  # [...]
end
....
```

I get the following error at the terminal:
```
NameError:
       undefined local variable or method `json' for #<RSpec::ExampleGroups::TasksAPI::POSTTasks::WhenTheRequestIsValid:0x007f844f093320>
       Did you mean?  JSON
```
Thanks in advance for any help!

**Comment by jraczak** [comment]
Also of note, if I move it to exactly where you have it in your `rails_helper.rb`, I get the following different error:

```
An error occurred while loading ./spec/requests/tasks_spec.rb.
Failure/Error: config.include RequestSpecHelper, type: :request

NameError:
  uninitialized constant RequestSpecHelper
```

**Comment by akabiru** [comment]
Hi @jraczak, at first glance please note that `# [...]` defines existing code blocks that have been left out to minimize the file size. Also the `json` method is a helper defined in support. So make sure you have that as well.

Refs: https://github.com/akabiru/todos-api/blob/master/spec/rails_helper.rb
https://github.com/akabiru/todos-api/blob/master/spec/support/request_spec_helper.rb

**Comment by jraczak** [comment]
Thanks for the response. Yes, I defined the json helper method in spec/support/request_spec_helper as per the tutorial. My `rails_helper` seems to have all the requisites. Any ideas?

**Comment by jraczak** [comment]
So I don't know if this is just for me for some reason, but I needed to explicitly load the file in rails_helper with `require 'support/request_spec_helper'`. I could have missed this in the tutorial, but I don't see it in your rails_helper file.

**Comment by akabiru** [comment]
@jraczak all files in `support` are autoloaded here https://github.com/akabiru/todos-api/blob/master/spec/rails_helper.rb#L23 . 🙂

**Comment by jraczak** [comment]
Ah, there it is. In the tutorial the language was `comment out the...` and so I had it commented out in my file. Thanks!
