### ISSUE TITLE
Error in http_auth_header method of AuthorizeApiRequest

### ISSUE THREAD

**Issue by jraczak** [akabiru/todos-api#4]
I've tried a full copy/paste of your file to ensure I didn't miss anything (I've reverted back to my version) and the same error persists.

`expected ExceptionHandler::MissingToken with "Missing token", got #<TypeError: no implicit conversion of String into Integer>`

This is being thrown on this line:

`if headers['Authorization'].present?`

Totally stumped on this!

**Comment by jraczak** [comment]
Wanted to bump this issue. I've done some logging for `headers['Authorization']` and it looks like everything that should be there is. Am I missing something somewhere else in the config? Thanks in advance for any guidance you can give.

```
Failures:

  1) AuthorizeApiRequest#call when invalid request when missing token raises a MissingToken error
     Failure/Error:
       expect { invalid_request_obj.call }
                 .to raise_error(ExceptionHandler::MissingToken, 'Missing token')
     
       expected ExceptionHandler::MissingToken with "Missing token", got #<TypeError: no implicit conversion of String into Integer> with backtrace:
         # ./app/auth/authorize_api_request.rb:32:in `[]'
         # ./app/auth/authorize_api_request.rb:32:in `http_auth_header'
         # ./app/auth/authorize_api_request.rb:28:in `decoded_auth_token'
         # ./app/auth/authorize_api_request.rb:17:in `user'
         # ./app/auth/authorize_api_request.rb:8:in `call'
         # ./spec/auth/authorize_api_request_spec.rb:26:in `block (6 levels) in <top (required)>'
         # ./spec/auth/authorize_api_request_spec.rb:26:in `block (5 levels) in <top (required)>'
     # ./spec/auth/authorize_api_request_spec.rb:26:in `block (5 levels) in <top (required)>'
```

**Comment by akabiru** [comment]
@jraczak Will get back to you shortly on this.

**Comment by akabiru** [comment]
Could you pry into `headers['Authoraztion']` to inspect. Better yet, you could share a link to your GH repo.

**Comment by jraczak** [comment]
@akabiru Sure thing, I've added you to the repo which you can find here: https://github.com/jraczak/flow-api

**Comment by akabiru** [comment]
Hey man, hope you managed to sort it out. Sorry I didn't get a chance to help out much. 😕
