### ISSUE TITLE
Error negative test with token invalid

### ISSUE THREAD

**Issue by zhiephie** [akabiru/todos-api#5]
How to handle error using fake token?

Original token: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1MDI4NzkwNjl9.LHBLFECjHhvYBJL9n4zUydW94eDBpgz8g5MUiTsvuBU`

Fake token: `syJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1MDI4NzkwNjl9.LHBLFECjHhvYBJL9n4zUydW94eDBpgz8g5MUiTsvuBU`

```
 http :3000/todos \ 
Authorization:'syJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1MDI4NzkwNjl9.LHBLFECjHhvYBJL9n4zUydW94eDBpgz8g5MUiTsvuBU'
HTTP/1.1 500 Internal Server Error
Content-Length: 11876
Content-Type: application/json; charset=UTF-8
X-Request-Id: aeb06724-91dc-463d-9999-f4d93abdd0aa
X-Runtime: 0.036293

{
    "error": "Internal Server Error", 
    "exception": "#<JWT::DecodeError: Invalid segment encoding>", 
    "status": 500, 
    "traces": {
        "Application Trace": [
            {
                "id": 5, 
                "trace": "app/lib/json_web_token.rb:15:in `decode'"

```

**Comment by akabiru** [comment]
Hi @zhiephie, thanks for catching that. We'll need to rescue from `JWT::DecodeError` at
https://github.com/akabiru/todos-api/blob/7965d0f0ecc1b2382054ccee2478ea9a0eec11a4/app/lib/json_web_token.rb#L17 as well, or better yet find out the JWT error superclass and rescue from that instead to mitigate unknown errors from happening.

Fancy raising a PR?

Edit:
correct branch link https://github.com/akabiru/todos-api/blob/8fb852cc44d1b579e3d29b182de238c2c2fefacf/app/lib/json_web_token.rb#L17

**Comment by akabiru** [comment]
Actually, just had a peek at the source code for `jwt`, `JWT::DecodeError` is the super error class for all decode failures. Thus, we only need to rescue from it.
https://github.com/jwt/ruby-jwt/blob/master/lib/jwt/error.rb#L1-L15

Let me know if you wanna raise a PR for this. 🙂

**Comment by zhiephie** [comment]
@akabiru Thanks for the reply, I don't know wanna raise a PR for this :smile:

**Comment by akabiru** [comment]
No worries. I'll keep this open till we resolve this. 🙂
