### ISSUE TITLE
Missing signout from the system

### ISSUE THREAD

**Issue by hmtanbir** [akabiru/todos-api#69]
Hi,
I am wondering that no sign out process in this api.
It will better if user can sign out using nullification the authorization token.
Could you please add the process @akabiru ?

**Comment by akabiru** [comment]
> Hi,
> I am wondering that no sign out process in this api.
> It will better if user can sign out using nullification the authorization token.
> Could you please add the process @akabiru ?

Hey Tanbir, that's been in the pipeline for a while now. I'm not sure how soon I can add that bit in as it requires substantial time and effort from my end. You're correct, a revoke strategy would be fitting IMO. In the meantime, you can check out [this article](http://waiting-for-dev.github.io/blog/2017/01/24/jwt_revocation_strategies/) by the author of [devise-jwt](https://github.com/waiting-for-dev/devise-jwt)

**Comment by akabiru** [comment]
https://github.com/akabiru/todos-api#please-note
