### ISSUE TITLE
Running into troubles when trying to run test for Items test cases

### ISSUE THREAD

**Issue by gderuki** [akabiru/todos-api#7]
> I literally have no clue where I could be wrong. I followed your tutorial step-by-step and get this output from **rspec** on my _POST_ test case:
> 
> ```
> Failure/Error: before { post "/posts/#{post_id}/items", params: {} }
>      
>      ArgumentError:
>        wrong number of arguments (given 2, expected 0)
> ```
> One more thing: I have renamed `Todo` model to `Post`. 
> Any ideas?

**UPDATE:** It seems that `RSpec` doesn't accept `Post` as model name, because of keyword `post` in your `before { post ... } ` expectation inside of `spec/requests/items_spec.rb`

**Comment by psanatov** [comment]
I actually couldn't recreate this strange ArgumentError second time after first crash.
