### ISSUE TITLE
Undefined local variable or method `json'

### ISSUE THREAD

**Issue by shelkovnikovad** [akabiru/todos-api#9]
I have failures when trying to create Todo API and run the command bundle exec rspec for running tests

![rubymine64_2017-12-17_19-48-17](https://user-images.githubusercontent.com/33757948/34081762-4796af38-e363-11e7-84b8-02d3d675bff9.png)

**Comment by akabiru** [comment]
Hey @shelkovnikovad , I'd confirm that the request helper is set up in `spec/support/request_spec_helper` and included in the rails_helper. Defined in [this section](https://scotch.io/tutorials/build-a-restful-json-api-with-rails-5-part-one#toc-controllers) 🙂

the request helper includes the method `json` that helps to parse the response body.
https://github.com/akabiru/todos-api/blob/master/spec/support/request_spec_helper.rb#L1-L5
https://github.com/akabiru/todos-api/blob/master/spec/rails_helper.rb#L72

**Comment by shelkovnikovad** [comment]
Thank you very much! And thanks for your amazing tutorial  :)

**Comment by akabiru** [comment]
No worries, glad you found it helpful! 🤘🏾🍻
